### ISSUE TITLE
[Bug] erreur activation

### ISSUE THREAD

**Issue by mika-nt28** [mika-nt28/Jeedom-Volets#199]
Mon Jan 15 19:34:32.853130 2018] [:error] [pid 1522] [client 192.168.1.30:51694] PHP Fatal error:  Uncaught Error: Call to undefined method VoletsCmd::CalculHeureEvent() in /var/www/html/plugins/Volets/core/class/Volets.class.php:641
Stack trace:
#0 /var/www/html/core/class/cmd.class.php(883): VoletsCmd->execute(NULL)
#1 /var/www/html/core/ajax/cmd.ajax.php(74): cmd->execCmd(NULL)
#2 {main}
  thrown in /var/www/html/plugins/Volets/core/class/Volets.class.php on line 641, referer: http://192.168.1.200/index.php?v=d&p=Volets&m=Volets&id=32
[Tue Jan 16 18:30:49.200196 2018] [:error] [pid 1933] [client 192.168.1.30:53497] PHP Fatal error:  Uncaught Error: Call to undefined method VoletsCmd::CalculHeureEvent() in /var/www/html/plugins/Volets/core/class/Volets.class.php:641
Stack trace:
#0 /var/www/html/core/class/cmd.class.php(883): VoletsCmd->execute(NULL)
#1 /var/www/html/core/ajax/cmd.ajax.php(74): cmd->execCmd(NULL)
#2 {main}
  thrown in /var/www/html/plugins/Volets/core/class/Volets.class.php on line 641, referer: http://192.168.1.200/index.php?v=d&m=Volets&p=Volets
[Tue Jan 16 19:42:38.412709 2018] [:error] [pid 1462] [client 192.168.1.30:54428] PHP Fatal error:  Uncaught Error: Call to undefined method VoletsCmd::CalculHeureEvent() in /var/www/html/plugins/Volets/core/class/Volets.class.php:641
Stack trace:
#0 /var/www/html/core/class/cmd.class.php(883): VoletsCmd->execute(NULL)
#1 /var/www/html/core/ajax/cmd.ajax.php(74): cmd->execCmd(NULL)
#2 {main}
  thrown in /var/www/html/plugins/Volets/core/class/Volets.class.php on line 641, referer: http://192.168.1.200/index.php?v=d&m=Volets&p=Volets
[Tue Jan 16 19:43:03.685482 2018] [:error] [pid 14984] [client 192.168.1.30:54438] PHP Fatal error:  Uncaught Error: Call to undefined method VoletsCmd::CalculHeureEvent() in /var/www/html/plugins/Volets/core/class/Volets.class.php:641
Stack trace:
#0 /var/www/html/core/class/cmd.class.php(883): VoletsCmd->execute(NULL)
#1 /var/www/html/core/ajax/cmd.ajax.php(74): cmd->execCmd(NULL)
#2 {main}
  thrown in /var/www/html/plugins/Volets/core/class/Volets.class.php on line 641, referer: http://192.168.1.200/index.php?v=d&m=Volets&p=Volets
Haut

**Comment by mika-nt28** [comment]
Correction apporté sur la beta (reproduit sur la stable)
